### PR TITLE
Feat: Add result page and readme

### PR DESCRIPTION
**Pull request by starver20**
Added result page and updated readme file.

### CODE REVIEW

**Review by vp5h — APPROVED** [review]
lgtm

**Review by Divya70 — APPROVED** [review]

**Review by Divya70 — APPROVED** [review]

**Review by VishalPatil18 — APPROVED** [review]
The code looks quite clean. Great work @starver20 👍

**Comment by starver20** [comment]
> lgtm

Wow, that's a new abbreviation for me.🙌🏻

**Comment by starver20** [comment]
> The code looks quite clean. Great work @starver20 +1

Thank you. @VishalPatil18

**Pull request merged**
